const Query = `
  type Query {
    repository(name: String!): Repository
    searchRepositories(query: String!): [Repository]
    allContributors: [Contributor]
    allUsers: [User]
  }
`

export default Query