const typeDef = `
  type User {
    id: ID!
    login: String
    avator_url: String
    html_url: String
    type: String
  }
`

const resolvers = {
  Query: {
    
  }
}

export default {
  typeDef,
  resolvers
}